#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";

const DATABASE_PATH = "./maptap_raw_database_20260821.json"
const OUTPUT_PATH = "./all_locs_maptap.json";

let origDatabase;

let iso2ToCountryName = {
	"AF":"Afghanistan",
	"AX":"Aland Islands",
	"AL":"Albania",
	"DZ":"Algeria",
	"AS":"American Samoa",
	"AD":"Andorra",
	"AO":"Angola",
	"AI":"Anguilla",
	"AQ":"Antarctica",
	"AG":"Antigua and Barbuda",
	"AR":"Argentina",
	"AM":"Armenia",
	"AW":"Aruba",
	"AU":"Australia",
	"AT":"Austria",
	"AZ":"Azerbaijan",
	"BS":"Bahamas",
	"BH":"Bahrain",
	"BD":"Bangladesh",
	"BB":"Barbados",
	"BY":"Belarus",
	"BE":"Belgium",
	"BZ":"Belize",
	"BJ":"Benin",
	"BM":"Bermuda",
	"BT":"Bhutan",
	"BO":"Bolivia",
	"BA":"Bosnia and Herzegovina",
	"BW":"Botswana",
	"BV":"Bouvet Island",
	"BR":"Brazil",
	"IO":"British Indian Ocean Territory",
	"BN":"Brunei",
	"BG":"Bulgaria",
	"BF":"Burkina Faso",
	"BI":"Burundi",
	"KH":"Cambodia",
	"CM":"Cameroon",
	"CA":"Canada",
	"CV":"Cape Verde",
	"KY":"Cayman Islands",
	"CF":"Central African Republic",
	"TD":"Chad",
	"CL":"Chile",
	"CN":"China",
	"CX":"Christmas Island",
	"CC":"Cocos (Keeling) Islands",
	"CO":"Colombia",
	"KM":"Comoros",
	"CG":"Rep. of the Congo",
	"CD":"Dem. Rep. of the Congo",
	"CK":"Cook Islands",
	"CR":"Costa Rica",
	"CI":"Côte d'Ivoire",
	"HR":"Croatia",
	"CU":"Cuba",
	"CY":"Cyprus",
	"CZ":"Czech Republic",
	"DK":"Denmark",
	"DJ":"Djibouti",
	"DM":"Dominica",
	"DO":"Dominican Republic",
	"EC":"Ecuador",
	"EG":"Egypt",
	"SV":"El Salvador",
	"GQ":"Equatorial Guinea",
	"ER":"Eritrea",
	"EE":"Estonia",
	"ET":"Ethiopia",
	"FK":"Falkland Islands (Malvinas)",
	"FO":"Faroe Islands",
	"FJ":"Fiji",
	"FI":"Finland",
	"FR":"France",
	"GF":"French Guiana",
	"PF":"French Polynesia",
	"TF":"French Southern Territories",
	"GA":"Gabon",
	"GM":"The Gambia",
	"GE":"Georgia",
	"DE":"Germany",
	"GH":"Ghana",
	"GI":"Gibraltar",
	"GR":"Greece",
	"GL":"Greenland",
	"GD":"Grenada",
	"GP":"Guadeloupe",
	"GU":"Guam",
	"GT":"Guatemala",
	"GG":"Guernsey",
	"GN":"Guinea",
	"GW":"Guinea-Bissau",
	"GY":"Guyana",
	"HT":"Haiti",
	"HM":"Heard Island and McDonald Islands",
	"VA":"Vatican City",
	"HN":"Honduras",
	"HK":"Hong Kong",
	"HU":"Hungary",
	"IS":"Iceland",
	"IN":"India",
	"ID":"Indonesia",
	"IR":"Iran",
	"IQ":"Iraq",
	"IE":"Ireland",
	"IM":"Isle of Man",
	"IL":"Israel",
	"IT":"Italy",
	"JM":"Jamaica",
	"JP":"Japan",
	"JE":"Jersey",
	"JO":"Jordan",
	"KZ":"Kazakhstan",
	"KE":"Kenya",
	"KI":"Kiribati",
	"KP":"North Korea",
	"KR":"South Korea",
	"XK":"Kosovo",
	"KW":"Kuwait",
	"KG":"Kyrgyzstan",
	"LA":"Laos",
	"LV":"Latvia",
	"LB":"Lebanon",
	"LS":"Lesotho",
	"LR":"Liberia",
	"LY":"Libya",
	"LI":"Liechtenstein",
	"LT":"Lithuania",
	"LU":"Luxembourg",
	"MO":"Macao",
	"MK":"North Macedonia",
	"MG":"Madagascar",
	"MW":"Malawi",
	"MY":"Malaysia",
	"MV":"Maldives",
	"ML":"Mali",
	"MT":"Malta",
	"MH":"Marshall Islands",
	"MQ":"Martinique",
	"MR":"Mauritania",
	"MU":"Mauritius",
	"YT":"Mayotte",
	"MX":"Mexico",
	"FM":"Micronesia",
	"MD":"Moldova",
	"MC":"Monaco",
	"MN":"Mongolia",
	"ME":"Montenegro",
	"MS":"Montserrat",
	"MA":"Morocco",
	"MZ":"Mozambique",
	"MM":"Myanmar",
	"NA":"Namibia",
	"NR":"Nauru",
	"NP":"Nepal",
	"NL":"Netherlands",
	"AN":"Netherlands Antilles",
	"NC":"New Caledonia",
	"NZ":"New Zealand",
	"NI":"Nicaragua",
	"NE":"Niger",
	"NG":"Nigeria",
	"NU":"Niue",
	"NF":"Norfolk Island",
	"MP":"Northern Mariana Islands",
	"NO":"Norway",
	"OM":"Oman",
	"PK":"Pakistan",
	"PW":"Palau",
	"PS":"Palestine",
	"PA":"Panama",
	"PG":"Papua New Guinea",
	"PY":"Paraguay",
	"PE":"Peru",
	"PH":"Philippines",
	"PN":"Pitcairn",
	"PL":"Poland",
	"PT":"Portugal",
	"PR":"Puerto Rico",
	"QA":"Qatar",
	"RE":"Reunion",
	"RO":"Romania",
	"RU":"Russia",
	"RW":"Rwanda",
	"BL":"Saint Barthelemy",
	"SH":"Saint Helena",
	"KN":"Saint Kitts and Nevis",
	"LC":"Saint Lucia",
	"MF":"Saint Martin",
	"PM":"Saint Pierre and Miquelon",
	"VC":"Saint Vincent and the Grenadines",
	"WS":"Samoa",
	"SM":"San Marino",
	"ST":"Sao Tome and Principe",
	"SA":"Saudi Arabia",
	"SN":"Senegal",
	"RS":"Serbia",
	"SC":"Seychelles",
	"SL":"Sierra Leone",
	"SG":"Singapore",
	"SK":"Slovakia",
	"SI":"Slovenia",
	"SB":"Solomon Islands",
	"SO":"Somalia",
	"ZA":"South Africa",
	"GS":"South Georgia and the South Sandwich Islands",
	"ES":"Spain",
	"LK":"Sri Lanka",
	"SD":"Sudan",
	"SR":"Suriname",
	"SJ":"Svalbard and Jan Mayen",
	"SZ":"Eswatini",
	"SE":"Sweden",
	"SS":"South Sudan",
	"CH":"Switzerland",
	"SY":"Syria",
	"TW":"Taiwan",
	"TJ":"Tajikistan",
	"TZ":"Tanzania",
	"TH":"Thailand",
	"TL":"Timor-Leste",
	"TG":"Togo",
	"TK":"Tokelau",
	"TO":"Tonga",
	"TT":"Trinidad and Tobago",
	"TN":"Tunisia",
	"TR":"Turkey",
	"TM":"Turkmenistan",
	"TC":"Turks and Caicos Islands",
	"TV":"Tuvalu",
	"UG":"Uganda",
	"UA":"Ukraine",
	"AE":"United Arab Emirates",
	"GB":"United Kingdom",
	"US":"United States",
	"UM":"United States Outlying Islands",
	"UY":"Uruguay",
	"UZ":"Uzbekistan",
	"VU":"Vanuatu",
	"VE":"Venezuela",
	"VN":"Vietnam",
	"VG":"British Virgin Islands",
	"VI":"U.S. Virgin Islands",
	"WF":"Wallis and Futuna",
	"EH":"Western Sahara",
	"YE":"Yemen",
	"ZM":"Zambia",
	"ZW":"Zimbabwe"
};

let countryNameToIso2 = Object.fromEntries(
    Object.entries(iso2ToCountryName).map(([key, value]) => [value, key])
);

let maptapSpecialCodes = {
    "Scotland": "GB",
    "England": "GB",
    "Northern Ireland": "GB",
    "Wales": "GB",
    "Ivory Coast": "CI",
    "Türkiye": "TR",
    "Gambia": "GM",
    "Czechia": "CZ",
    "Guinea Bissau": "GW",
    "Republic of the Congo": "CG",
    "Democratic Republic of the Congo": "CD",
    "Georgia (Country)": "GE",
    "Tahiti": "PF",
    "Falkland Islands": "FK",
    "East Timor": "TL",
    "US Virgin Islands": "VI",
    "Turks & Caicos": "TC",
    "Federated States of Micronesia": "FM",
    "South Georgia": "GS",
    "Saint Helena, Ascension and Tristan da Cunha": "SH",
    "Tristan da Cunha": "SH",
    "Pitcairn Islands": "PN",
	"Saint-Pierre and Miquelon": "PM",
	"Saint Barthélemy": "BL"
}

countryNameToIso2 = {...countryNameToIso2, ...maptapSpecialCodes};

let unknownCountries = new Set();

async function main() {
    origDatabase = JSON.parse(await readFile(DATABASE_PATH, "utf-8"));

    console.log(`${DATABASE_PATH} - Original cities: ${origDatabase.length}`);

    const newCities = origDatabase.filter(x => x.disabled != true).map((o) => {
		let nameArr = o.name.split(", ");
        let name = nameArr[0];
        let countryCode;
        let countryOfCity = o.country.includes("/") ? o.country.split("/")[0] : o.country;

        if (Object.hasOwn(countryNameToIso2, countryOfCity)) {
            countryCode = countryNameToIso2[countryOfCity];
        } else {
            unknownCountries.add(o.country);
            return null;
        }

        let admin = null;
		if (Object.hasOwn(o, "admin")) {
			admin = o.admin;
		} else if (nameArr.length >= 3) {
			admin = nameArr[1];
		}

		let population = Object.hasOwn(o, "population") ? o.population : null;
        return [name, countryCode, o.lat, o.lng, admin, o.type, o.difficultyLevel, population];
    }).filter(x => x!=null);

    console.log(`Unknown countries: \n${Array.from(unknownCountries).join("\n")}`);    
    console.log(`${OUTPUT_PATH} - Filtered cities: ${newCities.length}`);
    await writeFile(OUTPUT_PATH, JSON.stringify(newCities), "utf-8");
}
main();